# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13I5K6sKBF7q8UO_3mHe6XD-VTl62slpW
"""

import numpy as np
from math import *
from matplotlib import pyplot as plt

def circ_gen(C,r):
	len = 1000
	theta = np.linspace(0,2*np.pi,len)
	x_circ = np.zeros((2,len))
	x_circ[0,:] = r*np.cos(theta)
	x_circ[1,:] = r*np.sin(theta)
	x_circ = (x_circ.T + C).T
	return x_circ

C1 = np.array([2,-5/2])
f1 = 6
r1 = np.sqrt(np.linalg.norm(C1)**2 - f1)

C2 = np.array([5/2,-3])
f2 = 7
r2 = np.sqrt(np.linalg.norm(C2)**2 - f2)

C3 = np.array([-1/2,-1/2])
f3 = -1
r3 = np.sqrt(np.linalg.norm(C3)**2 - f3)

a = np.array([[4, -5, -1], [5, -6, -1], [-1, -1, -1]])
b = np.array([6, 7, -1])
x = np.linalg.solve(a, b)
C = x[:-1]
f = x[-1]
r = np.sqrt(np.linalg.norm(C)**2 - f)
#print(C,f,r,r1,r2,r3)
print('c =', C,'f =',f)

x_circ1 = circ_gen(C1,r1)
x_circ2 = circ_gen(C2,r2)
x_circ3 = circ_gen(C3,r3)
x_circ = circ_gen(C,r)

plt.grid()
plt.axis('equal')
plt.xlabel('x')
plt.ylabel('y')

# plotting the circle
plt.plot(x_circ1[0,:],x_circ1[1,:],label='$S_1=0$')
plt.plot(x_circ2[0,:],x_circ2[1,:],label='$S_2=0$')
plt.plot(x_circ3[0,:],x_circ3[1,:],label='$S_3=0$')
plt.plot(x_circ[0,:],x_circ[1,:],label='$S=0$')



plt.legend()